---
title: "HW 6"
author: "Kelly Wang"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Problem 1
```{r import_data}
# load the data in
birthweight_data=
  read_csv(file= "./data/birthweight.csv") 

#tidy data
birthweight_tidy = 
  birthweight_data%>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(
    babysex=recode(babysex, '1'= 'male', '2'='female'),
    babysex=as.factor(babysex),
    babysex=fct_relevel(babysex,"male", "female"),
    bhead=as.numeric(bhead),
    blength=as.numeric(blength),
    bwt=as.numeric(bwt),
    delwt=as.numeric(delwt),
    fincome=as.numeric(fincome), 
    frace=recode(frace, '1'='White', '2'= 'Black', '3'='Asian', '4'='Puerto Rican', '8'='Other', '9'='Unknown'),
    frace=as.factor(frace),
    frace=fct_relevel(frace,"White", "Black", "Asian", "Puerto Rican", "Other", "unknown"),
    gaweeks=as.numeric(gaweeks),
    malform=recode(malform, '0' = "absent", '1' = "present"),
    malform=as.factor(malform),
    malform=fct_relevel(malform, "absent", "present"),
    menarche=as.numeric(menarche),
    mheight=as.numeric(mheight),
    momage=as.numeric(momage),
    mrace=recode(mrace,'1' = 'White', '2' = 'Black', '3' = 'Asian', '4' = 'Puerto Rican', ' 8' = 'Other'),
    mrace=as.factor(mrace),
    parity=as.numeric(parity), 
    pnumlbw=as.numeric(pnumlbw),
    pnumgsa=as.numeric(pnumgsa),
    ppbmi = as.numeric(ppbmi),
    ppwt=as.numeric(ppwt),
    smoken=as.numeric(smoken),
    wtgain=as.numeric(wtgain)
  )
  
  
```

